language: java
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

notifications:
  email: true

notifications:
  webhooks:
    - https://idobata.io/hook/22ff3a1b-28ad-49e9-8fda-3cfc8493f32a
    
env:
  matrix:
    - ANDROID_TARGET=android-19 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-19 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    # fail x86 image because of no starting emulator
    - ANDROID_TARGET=android-19 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-19 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=x86
    - ANDROID_TARGET=android-19 EMULATOR_TARGET=2 ANDROID_SDKS=${ANDROID_TARGET},addon-google_apis-google-19,android-19,build-tools-19.0.3,sysimg-19 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    # fail x86 image because of no starting emulator
#    - ANDROID_TARGET=addon-google_apis_x86-google-19 EMULATOR_TARGET=2 ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-19,"addon-google_apis_x86-google-19" ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=x86
    - ANDROID_TARGET=android-18 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-18 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-18 EMULATOR_TARGET=2 ANDROID_SDKS=${ANDROID_TARGET},addon-google_apis-google-18,build-tools-19.0.3,sysimg-18 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-17 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17 EMULATOR_TARGET=2 ANDROID_SDKS=${ANDROID_TARGET},addon-google_apis-google-17,build-tools-19.0.3,sysimg-17 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-17 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=mips
    - ANDROID_TARGET=android-16 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-16 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-16 EMULATOR_TARGET=2 ANDROID_SDKS=${ANDROID_TARGET},addon-google_apis-google-16,build-tools-19.0.3,sysimg-16 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-16 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-16 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=mips
    - ANDROID_TARGET=android-15 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-15 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-15 EMULATOR_TARGET=2 ANDROID_SDKS=${ANDROID_TARGET},addon-google_apis-google-15,build-tools-19.0.3,sysimg-15 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-15 EMULATOR_TARGET=${ANDROID_TARGET} ANDROID_SDKS=${ANDROID_TARGET},android-19,build-tools-19.0.3,sysimg-15 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=mips

before_install:
    # Install base Android SDK and components
    - sudo apt-get install -qq libstdc++6:i386 lib32z1
    - export COMPONENTS=${ANDROID_SDKS}
    #build-tools-19.0.1,android-19,sysimg-19,extra-android-support,extra-google-google_play_services,extra-google-gcm,build-tools-19.0.3,extra-google-m2repository,extra-android-m2repository
    - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-1/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
    - source ~/.android-sdk-installer/env
 
    # Install required Android components.
    - android list sdk --extended -a
    - android list target

    # Create and start emulator
    - export AVD_NAME=test
#    - echo no | android create avd --force -n test -t ${ANDROID_TARGET} --abi ${ANDROID_ABI}
#    - echo no | android create avd --force -n test -t ${EMULATOR_TARGET}
    - if [ "${ANDROID_TARGET}" = android-19 ]; then echo no | android create avd --force -n ${AVD_NAME} -t ${EMULATOR_TARGET}  --abi ${ANDROID_ABI};else echo no | android create avd --force -n ${AVD_NAME} -t ${EMULATOR_TARGET} ;fi
    - emulator -avd test -no-skin -no-audio -no-window &
    
    
    # Make sure the emulator has started before running tests
    - wait_for_emulator

script:
 - android update project -p . --subprojects -t ${ANDROID_TARGET}
 - ant -f build.xml emma debug install
 - ant -f tests/build.xml emma debug install test
 
